version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest


    working_directory: ~/project
    branches:
      only:
        - develop
        - master

    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            yarn
      - run:
          name: "Execute tests"
          command: |
            yarn test -- --ci --collectCoverage
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
      - store_artifacts:
          path: coverage
